### ISSUE TITLE
Practica de Operaciones basicas

### ISSUE THREAD

**Issue by RichiMB** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-RichiMB#1]
[Practica_de_Operaciones_Basicas_JRMB.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-RichiMB/files/7174923/Practica_de_Operaciones_Basicas_JRMB.pdf)

**Comment by Arlet04** [comment]
Portada (excelente) contiene todos los datos requeridos 25 puntos
Procedimiento (suficiente) contiene ejemplos pero no basta ya que faltó explicar el procedimiento de cada uno de ellos 17 puntos
Figuras, ilustraciones y fotografías (suficiente)  muestra unas cuantas imágenes fotografías 17 puntos
Resultados y conclusiones (insuficiente) no  contiene conclusión ni resultados 0 puntos
Total: 59/100
calificación: 11.8% / 20%
calificado por: Jeanette Arlet Salazar Nicolás

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
